version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - NODE_ENV=production
    volumes:
      - ./server/contact_db.sqlite:/app/contact_db.sqlite
    restart: on-failure:5
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 